-- ============================================================
-- ecotour 데이터베이스 스키마 (참고용 DDL)
-- 실제 스키마는 JPA/Hibernate가 엔티티로부터 자동 생성합니다
-- (spring.jpa.hibernate.ddl-auto=create-drop). 본 파일은 문서/참고용.
-- 방언: H2 (in-memory). 시드 데이터는 src/main/resources/data.sql 참고.
-- ============================================================

-- 관광지
CREATE TABLE attraction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    description      VARCHAR(1000),
    category         VARCHAR(20)  NOT NULL,   -- COAST | MOUNTAIN | HISTORY | MINE_CULTURE | CAVE | OTHER
    latitude         DOUBLE,
    longitude        DOUBLE,
    address          VARCHAR(200),
    congestion_level VARCHAR(10)  NOT NULL,   -- LOW | MEDIUM | HIGH
    local_gem        BOOLEAN      NOT NULL,
    created_at       TIMESTAMP    NOT NULL
);

-- 사용자(관광객)
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(100) NOT NULL UNIQUE,
    nickname        VARCHAR(50)  NOT NULL,
    preferred_theme VARCHAR(20),              -- ECO | EXPERIENCE | HEALING | FAMILY | HISTORY_CULTURE
    created_at      TIMESTAMP    NOT NULL
);

-- 스탬프 코스
CREATE TABLE course (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    theme       VARCHAR(20)  NOT NULL
);

-- 코스 상세(코스-관광지 연결 + 방문 순서)
CREATE TABLE course_detail (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT NOT NULL,
    attraction_id BIGINT NOT NULL,
    visit_order   INT    NOT NULL,
    CONSTRAINT fk_cd_course     FOREIGN KEY (course_id)     REFERENCES course(id),
    CONSTRAINT fk_cd_attraction FOREIGN KEY (attraction_id) REFERENCES attraction(id),
    CONSTRAINT uq_course_order  UNIQUE (course_id, visit_order)
);

-- 방문/인증 기록
CREATE TABLE visit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    attraction_id BIGINT      NOT NULL,
    visit_type    VARCHAR(20) NOT NULL,       -- STAMP | ECO_ACTIVITY
    note          VARCHAR(500),
    visited_at    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_vl_user       FOREIGN KEY (user_id)       REFERENCES app_user(id),
    CONSTRAINT fk_vl_attraction FOREIGN KEY (attraction_id) REFERENCES attraction(id)
);

-- 리뷰/평점
CREATE TABLE review (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    attraction_id BIGINT       NOT NULL,
    rating        INT          NOT NULL,      -- 1 ~ 5
    content       VARCHAR(1000),
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT fk_rv_user       FOREIGN KEY (user_id)       REFERENCES app_user(id),
    CONSTRAINT fk_rv_attraction FOREIGN KEY (attraction_id) REFERENCES attraction(id)
);
